---
title: "extra_numbers"
author: "Ludovic Dutoit"
date: "01/09/2021"
output: github_document
---


This little document pick a couple of extra numbers for the ms according to an email with Lucila (Sep 1)


##Find how many genes are annotated:

```{sh}
#denovoassembly_annotation_reportNOMISSING.xls | cut -f 1 | sort | uniq
#denovoassembly_annotation_reportNOMISSING.xls | cut -f 1 > genes_with_some_annotation.txt

````


###find out how many of the genes that pass filtering are annotated

```{r}
annotated <- as.character(read.table("genes_with_some_annotation.txt")[,1])
passingfilter<-as.character(read.table("results_files/ALLgenes_results.txt",h=T)[,1])
length(which(passingfilter%in%annotated))
```

## Part 2: obtain a heatmap of specific 31 genes.




### Heatmaps focus genes

Those are the focus genes
```{r}
gene_names<-c("TRINITY_DN701_c1_g1","TRINITY_DN2157_c0_g1","TRINITY_DN4120_c0_g1","TRINITY_DN3177_c2_g1","TRINITY_DN11818_c0_g2","TRINITY_DN7661_c0_g1","TRINITY_DN1565_c1_g1","TRINITY_DN7762_c1_g1","TRINITY_DN9258_c0_g2","TRINITY_DN447_c0_g1","TRINITY_DN9246_c0_g1","TRINITY_DN69174_c0_g1","TRINITY_DN3816_c0_g1","TRINITY_DN434_c0_g1","TRINITY_DN14218_c0_g1","TRINITY_DN259_c1_g1","TRINITY_DN2294_c0_g1","TRINITY_DN15680_c0_g1","TRINITY_DN2563_c8_g1","TRINITY_DN576_c0_g2","TRINITY_DN432_c0_g1","TRINITY_DN2384_c0_g1","TRINITY_DN22213_c0_g1","TRINITY_DN721_c0_g2","TRINITY_DN1800_c0_g1","TRINITY_DN3244_c0_g1","TRINITY_DN10366_c0_g1","TRINITY_DN4408_c0_g2","TRINITY_DN85011_c0_g1","TRINITY_DN17646_c0_g1","TRINITY_DN48_c0_g1","TRINITY_DN3798_c0_g1")
```

Run the modelling
```{r}
library(tidyr)
library(DESeq2)
library(pheatmap)
library(stringr)
library(ggplot2)
library(dplyr)
library(matrixStats)
library(pheatmap)
library(edgeR)
library("RColorBrewer")

counts=read.csv("results_files/RSEM_gene_counts.txt", sep="", head=T)
head(counts)
samples=cbind(colnames(counts),rep(c("silver","yellow"),each=6))
rownames(samples)<-samples[,1]
samples=as.data.frame(samples[,-1])
colnames(samples)<-"treatment"
treatment <- factor(rep(c("silver","yellow"),each=6))
des <- model.matrix(~treatment)
dge <- DGEList(counts=counts) 
keep <- filterByExpr(counts, des) # inside function of limma aware of the design to remove rad counts
dge <- dge[keep,keep.lib.sizes=FALSE]

dge<- calcNormFactors(dge)
print("After filtering, kept a matrix of X genes by Y samples:")
dim(dge) 
logCPM <- cpm(dge, log=TRUE)
```

Isolate those focus genes:

```{r}
dds=DESeqDataSetFromMatrix(countData = round(dge$counts),colData = samples,design = ~ treatment)
rld <- rlog(dds, blind=F)

genes_ofinterest<-c()
focus<-logCPM[rownames(logCPM)%in%gene_names,]
##Heatmap of significant genes
mat<-assay(rld)[which(rownames(assay(rld))%in%gene_names),]

mat<-focus
mat <- mat - rowMeans(mat) 

colnames(mat)<-colnames(focus)

#and saving
pheatmap(mat,show_rownames = T,cellwidth=5,cellheight=5,border_color="lightgrey",cluster_row=T,cluster_col=F,fontsize=6) 


pdf("heatmapfocusgenes.pdf")
pheatmap(mat,show_rownames = T,cellwidth=5,cellheight=5,border_color="lightgrey",cluster_row=T,cluster_col=F,fontsize=6) 
dev.off()
#easy to visualize rownames
```

